### ISSUE TITLE
Check out my remake of the list (not an issue)

### ISSUE THREAD

**Issue by atashi764** [DominoKorean/Render-dragon-shader-list#23]
hey there, i tried remaking the list you can see samples https://github.com/atashi764/rd-shader-list/blob/atashi764/README.md

if you like it i will be glad continuing with the same style with some minor changes later

**Comment by DominoKorean** [comment]
Your document is highly readable and looks very neat, but it differs significantly from what I prioritize when editing the RenderDragon shader list, making it difficult for me to use. While the RenderDragon shader list does contain long passages in English, it is used by people from various countries, so I aim to make it as intuitive and organized as possible. Therefore, sections like **Heads up!** in the header might be hard for people from other countries to understand in context. 

Additionally, players need to be able to directly access the specific shader through hyperlinks in the header, so using collapsible features is not ideal. There is also some incorrect information; while RenderDragon negatively affects most low-end devices, it does not affect some devices at all, so it would be inaccurate to state otherwise. 

However, since I am not yet comfortable with English, I might incorporate some parts of your version into my work. Thank you very much for your excellent suggestion.

**Comment by atashi764** [comment]
don't worry... it's just a concept. i will do hyperlinks and simplifying too

**Comment by atashi764** [comment]
you may take a look again :D

https://github.com/atashi764/rd-shader-list/blob/atashi764/readme_wip.md#betterrenderdragon

**Comment by DominoKorean** [comment]
Your README_wip is now added to the Render Dragon contents.
* [README_wip](https://github.com/DominoKorean/Render-dragon-shader-list?tab=readme-ov-file#readme_wip)
