### ISSUE TITLE
beta and stable separation from patchedapp.md + update mediafire links?

### ISSUE THREAD

**Issue by atashi764** [DominoKorean/Render-dragon-shader-list#40]
most people usually don't play beta versions. In #39 , I sorted the links by version... it would be better if betas are separated from stable versions. 

i saw a duplicate. but the links are different. `1.20.40.20`

[Q] what's different between these two?
![image](https://github.com/DominoKorean/Render-dragon-shader-list/assets/40156662/536a4a18-fe2a-49f4-b83f-268af0665c49)

and... the mediafire links look not really good. 

i suggest you to use links like this `https://www.mediafire.com/file/m7zmheqbp57qjv2/1.20.15.01_arm64_v8a_patched.apk/` instead of this `https://download2392.mediafire.com/wvgzyzvcbxigzDVWyod3wQoIRxOSNZBR8HSn6ot3P3EHtJYAlYLovC41RSkNuTUfxRn6I4aca85owxwZOlM6koDJg-HXyZWCvWAtKSiHvWmStWuo-5Y61T-4yi-bT3udlwyUkqGOKWa1kR-Ay4wHiVuY9gXpEhqPw-zKuXtGkaPV/zuumsd4vl1kyrhq/1.20.30.20_arm64_v8a_patched.apk`

i guess you're doing this for direct downloads but i like smaller links.

and about draco patched apks...
i can directly download from play store and patch it with draco and upload apk for you. and also implement the same custom features Wind's Scion Hub. *only if you allow*

**Comment by DominoKorean** [comment]
I've been using that method since the early days, so I just continue using it as is. (In fact, using that method does not result in immediate file downloads.) Later, I will change all links to standard Mediafire links.

As for the old version... well, you can just ignore it. That version is from before some bugs were fixed. It’s a habit I developed when I started documenting all versions while creating the RenderDragon shader list.

For the patched app, I plan to add a guide on using Draco Patch instead of providing it directly.
