### ISSUE TITLE
Why isn't there a 32bit version for Minecraft?

### ISSUE THREAD

**Issue by ShopRobloxsieuuytin** [DominoKorean/Render-dragon-shader-list#8]
Why isn't there a 32bit version for Minecraft?

**Comment by DominoKorean** [comment]
I understand that Endermanyk doesn't have a 32-bit phone due to that reason. For details, please inquire on the YSSBE Discord.
https://discord.gg/yss
![Screenshot_20231030_152459_Discord](https://github.com/DominoKorean/Render-dragon-shader-list/assets/110039366/8a553895-7fd1-40f8-b889-c93429cf06bb)
